export const POST_COMMON_TASK_START = "POST_COMMON_TASK_START"
export const POST_COMMON_TASK_SUCCESS = "POST_COMMON_TASK_SUCCESS"
export const POST_COMMON_TASK_ERROR = "POST_COMMON_TASK_ERROR"

export const GET_COMMON_TASKS_START = "GET_COMMON_TASKS_START"
export const GET_COMMON_TASKS_SUCCESS = "GET_COMMON_TASKS_SUCCESS"
export const GET_COMMON_TASKS_ERROR = "GET_COMMON_TASKS_ERROR"

