export const GET_TO_DO_ITEMS_START = "GET_TO_DO_ITEMS_START"
export const GET_TO_DO_ITEMS_SUCCESS = "GET_TO_DO_ITEMS_SUCCESS"
export const GET_TO_DO_ITEMS_ERROR = "GET_TO_DO_ITEMS_ERROR"

export const POST_TO_DO_ITEM_START = "POST_TO_DO_ITEM_START"
export const POST_TO_DO_ITEM_SUCCESS = "POST_TO_DO_ITEM_SUCCESS"
export const POST_TO_DO_ITEM_ERROR = "POST_TO_DO_ITEM_ERROR"

export const DELETE_TO_DO_ITEM_START = "DELETE_TO_DO_ITEM_START"
export const DELETE_TO_DO_ITEM_SUCCESS = "DELETE_TO_DO_ITEM_SUCCESS"
export const DELETE_TO_DO_ITEM_ERROR = "DELETE_TO_DO_ITEM_ERROR"
